name: Assign author
on:
    pull_request:
        types: [opened, reopened]

jobs:
    assign-author:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: toshimaru/auto-author-assign@v1.6.2