name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Publish Web Extension
    runs-on: ubuntu-latest

    steps:
    - run: |
        echo The PR was merged
    - uses: actions/checkout@v1
    - run: |
        cd ../
        zip -r LeetTimer.zip LeetTimer
        ls -lah
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: ../LeetTimer.zip
        extension-id: ${{ secrets.EXTENSION_ID }}
        client-id: ${{ secrets.GAPI_CLIENT_ID }}
        client-secret: ${{ secrets.GAPI_CLIENT_SECRET }}
        refresh-token: ${{ secrets.GAPI_REFRESH_TOKEN }}